# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briclyn', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
