# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briclyn', '0003_userprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='customer_type',
            new_name='transaction_type',
        ),
    ]
