# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briclyn', '0004_auto_20160720_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
