# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briclyn', '0005_listing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(blank=True, choices=[('HOUSE', 'House'), ('OFFICE', 'Office'), ('APARTMENT', 'Apartment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('RENT', 'Rent'), ('SALE', 'Sale')], max_length=100),
        ),
    ]
