# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briclyn', '0006_auto_20160724_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='baths',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
