# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briclyn', '0007_auto_20160724_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
